### ISSUE TITLE
[feature] checksum api

### ISSUE THREAD

**Issue by palindrom615** [sdkman/sdkman-broker#1]
Hi! thanks for fascinating service.

is there any plan to provide api for checksum of sdk(whichever algorithm)?

**Comment by marc0der** [comment]
This is planned somewhere in the future. The fact that we are merely redirecting to others' binaries does make it difficult to perform checksums though (we don't serve the binaries ourselves). This is also difficult to pull off on the client side right now as we are reliant on scaled down bash with very few dependencies. 

Perhaps Rust will allow us to do the checksum verification (perhaps SHA-256) on the client side. This is still way off though.

Feel free to start a discussion on our [Slack](https://slack.sdkman.io) if you would like to see this as a feature in the future.

The issues on the individual services don't really get monitored so closing this.
